services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app_development -U postgres"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 127.0.0.1:5433:5432
    networks:
      default:
        aliases:
          - db
  app:
    build:
      context: .
    volumes:
      - app:/usr/src/app:cached
      - bundle:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - app
    command: rails server -b 0.0.0.0
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
  bundle:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/postgresql/14/data
